In [1]:
%pylab inline


Populating the interactive namespace from numpy and matplotlib


In [2]:
A = array([[0,1,1,0,0,0],[1,0,1,0,0,0],[1,1,0,1,0,0],[0,0,1,0,1,1],[0,0,0,1,0,1],[0,0,0,1,1,0]])
L = diag(A.sum(axis = 1))-A
eigenValues,eigenVectors = eig(L)

idx = eigenValues.argsort()   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]
eigenVectors[:,1]


array([ 0.46470513,  0.46470513,  0.26095647, -0.26095647, -0.46470513,
       -0.46470513])

In [4]:
T = diag(A.sum(axis = 1))
invT = diag(1.0/A.sum(axis = 1))
sqInvT = sqrt(invT) # T^{-1/2}
la = dot(sqInvT, dot(L, sqInvT))
eigenValues,eigenVectors = eig(la)

idx = eigenValues.argsort()   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]
eigenValues

array([ 0.        ,  0.20466635,  1.16666667,  1.5       ,  1.5       ,
        1.62866698])

In [8]:
A = array([[0,0,1,0],[0,0,0,1],[1,0,0,0],[0,1,0,0]])
T = diag(A.sum(axis = 1))
L = diag(A.sum(axis = 1))-A
invT = diag(1.0/A.sum(axis = 1))
sqInvT = sqrt(invT) # T^{-1/2}
la = dot(sqInvT, dot(L, sqInvT))
eigenValues,eigenVectors = eig(la)

idx = eigenValues.argsort()   
eigenValues = eigenValues[idx]
eigenVectors = eigenVectors[:,idx]
eigenValues

array([ 0.,  0.,  2.,  2.])