In [1]:
%pylab inline
#from http://www.math.tamu.edu/~dallen/linear_algebra/chpt6.pdf

Populating the interactive namespace from numpy and matplotlib


In [2]:
#QR method
A = array([[2,1,1],[1,2,1],[1,1,2]])
A

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [35]:
n = A.shape[0]
k = 0
d = A[:,k]/sum(A[:,k]**2)**0.5 #normalized first column
D = sum(d[k:]**2)**0.5
if(d[k]>0):
    D *= -1
v = zeros(n)
v[k] = (0.5*(1-d[k]/D))**0.5
p = - D * v[k]
for j in range(k+1, n):
    v[j] = d[j]/(2*p)

P = eye(n) - 2* outer(v,v)    
A2 = dot(P,A)
A2

array([[ -2.44948974e+00,  -2.04124145e+00,  -2.04124145e+00],
       [ -1.38777878e-16,   1.31649658e+00,   3.16496581e-01],
       [ -1.38777878e-16,   3.16496581e-01,   1.31649658e+00]])

In [36]:
k = 1
d = A2[:,k]/sum(A2[:,k]**2)**0.5 #normalized second column
D = sum(d[k:]**2)**0.5
if(d[k]>0):
    D *= -1
v = zeros(n)
v[k] = (0.5*(1-d[k]/D))**0.5

p = - D * v[k]
for j in range(k+1, n):
    v[j] = d[j]/(2*p)
    
P = eye(n) - 2* outer(v,v)    
A3 = dot(P,A2)
A3

array([[ -2.44948974e+00,  -2.04124145e+00,  -2.04124145e+00],
       [  1.67372418e-16,  -1.35400640e+00,  -6.15457455e-01],
       [ -1.02494256e-16,  -8.18572640e-18,   1.20604538e+00]])