In [3]:
%pylab inline
from scipy.linalg import lu


Populating the interactive namespace from numpy and matplotlib


In [4]:
A = array([[2,1,-1,8],[-3,-1,2,-11],[-2,1, 2, -3]])

In [5]:
A

array([[  2,   1,  -1,   8],
       [ -3,  -1,   2, -11],
       [ -2,   1,   2,  -3]])

In [6]:
a,b = lu(A, permute_l=True)
a

array([[-0.66666667,  0.2       ,  1.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.66666667,  1.        ,  0.        ]])

In [7]:
b


array([[ -3.        ,  -1.        ,   2.        , -11.        ],
       [  0.        ,   1.66666667,   0.66666667,   4.33333333],
       [  0.        ,   0.        ,   0.2       ,  -0.2       ]])

In [8]:
b[1] - b[2]*b[1][2]/b[2][2]

array([  0.00000000e+00,   1.66666667e+00,  -1.11022302e-16,
         5.00000000e+00])

In [9]:
L = array([[2,-1,-1],[-1,2,-1],[-1,-1,2]])
a,b = lu(L, permute_l=True)
b

array([[ 2. , -1. , -1. ],
       [ 0. ,  1.5, -1.5],
       [ 0. ,  0. ,  0. ]])

In [61]:
def row_echelon(L):
    n = L.shape[0]
    b = array([[float(L[i][j]) for j in range(L.shape[1])] for i in range(n)])
    b = around(b,6)  #cutting off at 6 decimal places
    for i in reversed(range(b.shape[0])):
        if(b[i][i] == 0):
            print("woh, zero")
            continue
        b[i] = b[i]/b[i][i]
        if(i != 0):
            for j in range(i):
                b[j] = b[j] - b[i]*b[j][i]/b[i][i]       
    return b

A = array([[2,1,-1,8],[-3,-1,2,-11],[-2,1, 2, -3]])
a,b = lu(A, permute_l=True)

print(row_echelon(b))
print(b)

[[ 1.        -0.        -0.         2.0000002]
 [ 0.         1.         0.         2.9999994]
 [ 0.         0.         1.        -1.       ]]
[[ -3.          -1.           2.         -11.        ]
 [  0.           1.66666667   0.66666667   4.33333333]
 [  0.           0.           0.2         -0.2       ]]


In [58]:
def gaussian_elim(L):
    n = L.shape[0]
    b = array([[float(L[i][j]) for j in range(L.shape[1])] for i in range(n)]) 
    for i in range(n):
        if(b[i][i] == 0):
            for k in range(i+1,n):
                if(b[i][k] != 0):
                    raise ValueError("Yikes!!! Have to do a swap")
            continue        
        for j in range(i+1,n):
            b[j] = b[j] - b[i]*b[j][i]/b[i][i]  
    return around(b,6) #cutting off at 6 decimal places

L = array([[2,-1,-1.0,0,0],[-1,2,-1,0,0],[-1,-1,2,0,0],[0,0,0,1,-1],[0,0,0,-1,1]])
gaussian_elim(L)

array([[ 2. , -1. , -1. ,  0. ,  0. ],
       [ 0. ,  1.5, -1.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. , -1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ]])

In [12]:
L = array([[2,-1,-1,0,0],[-1,2,-1,0,0],[-1,-1,2,0,0],[0,0,0,1,-1],[0,0,0,-1,1]])
a,b = lu(L, permute_l=True)
b
row_echelon(b)

woh, zero
woh, zero


array([[ 1.,  0., -1.,  0.,  0.],
       [ 0.,  1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
A = array([[2,1,-1,8],[-3,-1,2,-11],[-2,1, 2, -3]])
a = gaussian_elim(A)
a

array([[ 2. ,  1. , -1. ,  8. ],
       [ 0. ,  0.5,  0.5,  1. ],
       [ 0. ,  0. , -1. ,  1. ]])

In [48]:
def make_rand_weighted_L(n):
    A = abs(randn(n**2)).reshape(n,n)
    A += A.T
    np.fill_diagonal(A, 0)
    D = diag(A.sum(1))
    L = D - A
    return L

def make_rand_unweighted_L(n, p):
    A = [[0 for i in range(n)] for j in range(n)]
    for i in range(n):
        for j in range(i+1, n):
            if(rand()<p):
                A[i][j] = A[j][i] = 1
    A = array(A)            
    D = diag(A.sum(1))
    L = D - A
    return L                     
    

make_rand_weighted_L(4)
make_rand_unweighted_L(10,0.6)

array([[ 8, -1, -1, -1, -1, -1, -1, -1, -1,  0],
       [-1,  6, -1, -1,  0, -1,  0, -1, -1,  0],
       [-1, -1,  5, -1,  0, -1, -1,  0,  0,  0],
       [-1, -1, -1,  7, -1, -1,  0,  0, -1, -1],
       [-1,  0,  0, -1,  7, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1,  6,  0,  0,  0, -1],
       [-1,  0, -1,  0, -1,  0,  6, -1, -1, -1],
       [-1, -1,  0,  0, -1,  0, -1,  5, -1,  0],
       [-1, -1,  0, -1, -1,  0, -1, -1,  6,  0],
       [ 0,  0,  0, -1, -1, -1, -1,  0,  0,  4]])

In [70]:
def test():
    A = make_rand_weighted_L(7)
    a = gaussian_elim(A)
    b,c = lu(A, permute_l=True)
    return np.array_equal(row_echelon(a) ,row_echelon(c))
test()

woh, zero
woh, zero


True

In [50]:
A

array([[ 3.02806384, -0.79186279, -1.32849967, -0.90770137],
       [-0.79186279,  2.2564115 , -0.49011014, -0.97443857],
       [-1.32849967, -0.49011014,  2.73751134, -0.91890153],
       [-0.90770137, -0.97443857, -0.91890153,  2.80104147]])