In [5]:
%pylab inline
from scipy.linalg import lu


Populating the interactive namespace from numpy and matplotlib


In [98]:
A = array([[2,1,-1,8],[-3,-1,2,-11],[-2,1, 2, -3]])

In [53]:
A

array([[  2,   1,  -1,   8],
       [ -3,  -1,   2, -11],
       [ -2,   1,   2,  -3]])

In [102]:
a,b = lu(A, permute_l=True)
a

array([[-0.66666667,  0.2       ,  1.        ],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.66666667,  1.        ,  0.        ]])

In [103]:
b


array([[ -3.        ,  -1.        ,   2.        , -11.        ],
       [  0.        ,   1.66666667,   0.66666667,   4.33333333],
       [  0.        ,   0.        ,   0.2       ,  -0.2       ]])

In [69]:
b[1] - b[2]*b[1][2]/b[2][2]

array([  0.00000000e+00,   1.66666667e+00,  -1.11022302e-16,
         5.00000000e+00])

In [110]:
L = array([[2,-1,-1],[-1,2,-1],[-1,-1,2]])
a,b = lu(L, permute_l=True)
b

array([[ 2. , -1. , -1. ],
       [ 0. ,  1.5, -1.5],
       [ 0. ,  0. ,  0. ]])

In [108]:
def row_echelon(L):
    b = L[:] #weird... I can't seem to copy (do I need to go deep?)
    for i in reversed(range(b.shape[0])):
        if(b[i][i] == 0):
            print("woh, zero")
            continue
        b[i] = b[i]/b[i][i]
        if(i != 0):
            for j in range(i):
                b[j] = b[j] - b[i]*b[j][i]/b[i][i]       
    return b

A = array([[2,1,-1,8],[-3,-1,2,-11],[-2,1, 2, -3]])
a,b = lu(A, permute_l=True)

print(row_echelon(b))
print(b)

[[ 1. -0. -0.  2.]
 [ 0.  1.  0.  3.]
 [ 0.  0.  1. -1.]]
[[ 1. -0. -0.  2.]
 [ 0.  1.  0.  3.]
 [ 0.  0.  1. -1.]]


In [172]:
def gaussian_elim(L):
    n = L.shape[0]
    b = array([[float(L[i][j]) for j in range(L.shape[1])] for i in range(n)]) 
    for i in range(n):
        if(b[i][i] == 0):
            for k in range(i+1,n):
                if(b[i][k] != 0):
                    raise ValueError("Yikes!!! Have to do a swap")
            continue        
        for j in range(i+1,n):
            b[j] = b[j] - b[i]*b[j][i]/b[i][i]  
    return b

L = array([[2,-1,-1.0,0,0],[-1,2,-1,0,0],[-1,-1,2,0,0],[0,0,0,1,-1],[0,0,0,-1,1]])
gaussian_elim(L)

array([[ 2. , -1. , -1. ,  0. ,  0. ],
       [ 0. ,  1.5, -1.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  1. , -1. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ]])

In [128]:
L = array([[2,-1,-1,0,0],[-1,2,-1,0,0],[-1,-1,2,0,0],[0,0,0,1,-1],[0,0,0,-1,1]])
a,b = lu(L, permute_l=True)
b
row_echelon(b)

woh, zero
woh, zero


array([[ 1.,  0., -1.,  0.,  0.],
       [ 0.,  1., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [173]:
A = array([[2,1,-1,8],[-3,-1,2,-11],[-2,1, 2, -3]])
a = gaussian_elim(A)
a

array([[ 2. ,  1. , -1. ,  8. ],
       [ 0. ,  0.5,  0.5,  1. ],
       [ 0. ,  0. , -1. ,  1. ]])