In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
A = array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
A

array([[ 4,  1, -2,  2],
       [ 1,  2,  0,  1],
       [-2,  0,  3, -2],
       [ 2,  1, -2, -1]])

In [3]:
A = array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
for k in range(len(A)-1):
    n = len(A)
    a = A[:,k]
    lower_norm = sqrt(sum([a[i]**2 for i in range(k+1,n)]))
    alpha = - (sign(a[k+1])) * lower_norm
    r = sqrt(0.5*(alpha**2 - a[k+1]*alpha))
    w = zeros(n)
    w[k+1] = (a[k+1] - alpha)/(2*r)
    for i in range(k+2,n):
        w[i] = a[i]/(2*r)
    p = eye(n) - 2*outer(w,w.T)
    A = dot(dot(p,A),p)
around(A, 4)

array([[ 4.    , -3.    ,  0.    ,  0.    ],
       [-3.    ,  3.3333, -1.6667, -0.    ],
       [ 0.    , -1.6667, -1.32  , -0.9067],
       [ 0.    ,  0.    , -0.9067,  1.9867]])

In [31]:
def tamu_QR(a):
    #based on http://www.math.tamu.edu/~dallen/linear_algebra/chpt6.pdf
    #actually, Im totally messing it up... but it seems to work???
    #I think I understand why it works now
    A = a.astype(float)
    n = len(A)
    for j in range(20):
        for k in range(n-1):
            a = A[:,k]
            lower_norm = sqrt(sum([a[i]**2 for i in range(k,n)]))
            alpha = - (sign(a[k])) * lower_norm
            r = sqrt(0.5*(alpha**2 - a[k]*alpha))
            w = zeros(n)
            w[k] = (a[k] - alpha)/(2*r)
            for i in range(k+1,n):
                w[i] = a[i]/(2*r)
            p = eye(n) - 2*outer(w,w.T)
            R = dot(p,A)
            A = dot(R,p)

  
    return array([A[i][i] for i in range(n)])
    
    
A = array([[8,-2,-2],[-2,4,-2],[-2,-2,13]]) 
tamu_QR(A)    

array([ 13.87058484,   8.62043436,   2.5089808 ])

In [46]:
def tamu_QR2(a):
    #broken.... kind of confused
    #based on http://www.math.tamu.edu/~dallen/linear_algebra/chpt6.pdf
    A = a.astype(float)
    temp_A = a.astype(float)
    n = len(A)
    for j in range(40):
        Q = eye(n)
        for k in range(n-1):
            a = temp_A[:,k]
            lower_norm = sqrt(sum([a[i]**2 for i in range(k,n)]))
            alpha = - (sign(a[k])) * lower_norm
            r = sqrt(0.5*(alpha**2 - a[k]*alpha))
            w = zeros(n)
            w[k] = (a[k] - alpha)/(2*r)
            for i in range(k+1,n):
                w[i] = a[i]/(2*r)
            p = eye(n) - 2*outer(w,w.T)
            temp_A = dot(p, temp_A)
            Q = dot(p,Q)   
        R = dot(Q,A)
        A = dot(R,Q)
        temp_A = A.astype(float)

  
    return array([A[i][i] for i in range(n)])
    

A = array([[2,1,1],[1,2,1],[1,1,2]]) 
#A = array([[8,-2,-2],[-2,4,-2],[-2,-2,13]]) 
tamu_QR2(A)    

array([ 2.46703711,  1.47051509,  0.92393225])