In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
A = array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
A

array([[ 4,  1, -2,  2],
       [ 1,  2,  0,  1],
       [-2,  0,  3, -2],
       [ 2,  1, -2, -1]])

In [5]:
A = array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
for k in range(len(A)-1):
    n = len(A)
    a = A[:,k]
    lower_norm = sqrt(sum([a[i]**2 for i in range(k+1,n)]))
    alpha = - (sign(a[k+1])) * lower_norm
    r = sqrt(0.5*(alpha**2 - a[k+1]*alpha))
    w = zeros(n)
    w[k+1] = (a[k+1] - alpha)/(2*r)
    for i in range(k+2,n):
        w[i] = a[i]/(2*r)
    p = eye(n) - 2*outer(w,w.T)
    A = dot(dot(p,A),p)
around(A, 4)

array([[ 4.    , -3.    ,  0.    ,  0.    ],
       [-3.    ,  3.3333, -1.6667, -0.    ],
       [ 0.    , -1.6667, -1.32  , -0.9067],
       [ 0.    ,  0.    , -0.9067,  1.9867]])

In [13]:
A = array([[4,1,-2,2],[1,2,0,1],[-2,0,3,-2],[2,1,-2,-1]])
for k in range(len(A)-1):
    n = len(A)
    a = A[:,k]
    lower_norm = sqrt(sum([a[i]**2 for i in range(k,n)]))
    alpha = - (sign(a[k])) * lower_norm
    r = sqrt(0.5*(alpha**2 - a[k]*alpha))
    w = zeros(n)
    w[k] = (a[k] - alpha)/(2*r)
    for i in range(k+1,n):
        w[i] = a[i]/(2*r)
    p = eye(n) - 2*outer(w,w.T)
    A = dot(p,A)
    
around(A, 4)

array([[-5.    , -1.6   ,  3.6   , -2.2   ],
       [-0.    , -1.8547, -0.9489,  0.2804],
       [ 0.    , -0.    , -1.7719, -0.105 ],
       [-0.    ,  0.    , -0.    , -2.2517]])